// PLEASE CHANGE THE PORT NUMBER TO THE ONE CREATED WHEN YOU START THE APP
@baseUrl = https://localhost:7124/api/Users
@json = application/json
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.TEST_TOKEN_EXAMPLE

###  Get all users
GET {{baseUrl}}
Accept: {{json}}
Authorization: Bearer {{token}}


### EXAMPLE NOT AUTH
GET {{baseUrl}}
Accept: {{json}}



###  Get user by ID
GET {{baseUrl}}/1
Accept: {{json}}
Authorization: Bearer {{token}}

###  Create a new user
POST {{baseUrl}}
Content-Type: {{json}}
Authorization: Bearer {{token}}

{
  "name": "Diana",
  "email": "diana@example.com",
  "jobTitle": "Cloud Engineer"
}

###  Update user
PUT {{baseUrl}}/2
Content-Type: {{json}}
Authorization: Bearer {{token}}

{
  "name": "Bob Updated",
  "email": "bob_updated@example.com",
  "jobTitle": "Cybersecurity Specialist"
}

###  Remove user
DELETE {{baseUrl}}/3
Accept: {{json}}
Authorization: Bearer {{token}}

###  Get path call counter
GET {{baseUrl}}/routeCounter
Accept: {{json}}
Authorization: Bearer {{token}}
